### ISSUE TITLE
Compiler shows different output in "npm test" and the webpage (index.html)

### ISSUE THREAD

**Issue by aditya1c** [ucsd-cse231-w21/chocopy-wasm-compiler#72]
Hey,

Issue above can be replicated by just doing **print(abs(-2))**. The webpage shows answer as 1 but tests work fine.

Is anyone else facing this issue?

**Comment by jpolitz** [comment]
It looks like `abs` is different in `webstart.ts` and `import-object.test.ts`. @lsteffkojr @actomlinson might have an idea/suggestions

**Comment by jpolitz** [comment]
(Is it just `abs`, or lots of things?)

**Comment by aditya1c** [comment]
From what I've seen, it's only `abs`

**Comment by actomlinson** [comment]
Our [latest branch](https://github.com/actomlinson/chocopy-wasm-compiler/tree/big-nums-link-dev) will fix this, once it gets merged in all the imported functions will be added in repl.ts similar to #64

**Comment by actomlinson** [comment]
This issue should be resolved. `print(abs(-2))` for example now prints 2 and returns 2. @aditya1c @jpolitz

**Comment by jpolitz** [comment]
Yay! Thank you
