### ISSUE TITLE
Handling Zero-Sized Allocations

### ISSUE THREAD

**Issue by student-of** [ucsd-cse231-w21/chocopy-wasm-compiler#73]
Example (excerpt from test `many-ifs`):
```
class C(object):
  def f(self: C):
    print(method)
c: C = None
c = C()
```
The GC and allocators do not handle zero-sized allocations well, so one solution is to allocate a dummy word and use that as a handle. Any thoughts?

**Comment by jpolitz** [comment]
Not really, if it needs to have size, it needs to have size.
