### ISSUE TITLE
Webhook for fuzzing server

### ISSUE THREAD

**Issue by ptliu** [ucsd-cse231-w21/chocopy-wasm-compiler#76]
Can we get a webhook created that sends requests to python-to-wasm.edwjchen.com on port 11500, subscribed to the push event?

**Comment by jpolitz** [comment]
Can you give me a how-to? Maybe some screenshots? The less hunting in the interface I need to do the faster it will go.

**Comment by ptliu** [comment]
Go to Settings -> Webhook, should look something like below

![settings_webhook](https://user-images.githubusercontent.com/12316867/110677664-a6e27780-8192-11eb-868a-1cba5f2f3bc4.png)

Then, click on Add Webhook, which should look like the following

![settings_2_webhook](https://user-images.githubusercontent.com/12316867/110677735-ba8dde00-8192-11eb-8287-154ff457dfa1.PNG)

Make sure the settings match, and then create the webhook.

**Comment by jpolitz** [comment]
Done
